version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: fathers_app
    environment:
      - PORT=8000
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - mongo
    entrypoint: ["/app"]
  mongo:
    hostname: mongo
    container_name: fathers_mongo
    image: mongo:latest
    expose:
      - 27017
    ports:
      - 27017:27017
